### ISSUE TITLE
.env, .nvmrc, .npmrc

### ISSUE THREAD

**Issue by cyrilchapon** [entropitor/dotenv-cli#34] opened 2020-03-25 10:24 UTC
I have the following setup

_.npmrc_
```bash
@fortawesome:registry=https://npm.fontawesome.com/
//npm.fontawesome.com/:_authToken=${FA_TOKEN}

```

_.nvmrc_
```bash
v10.14.2

```

_.env_
```bash
FA_TOKEN=XXX
```

Running

```bash
dotenv nvm use
```

throws
```bash
env: node: No such file or directory
```

Already tried; same result :

```
dotenv "nvm use"
dotenv -- nvm use
dotenv -- "nvm use"
dotenv nvm use 10.14.2
```

**Comment by entropitor** [comment] 2020-03-25 10:29
I guess the problem is that `nvm` is not a real executable. Can you try 

```
dotenv -- bash -c "nvm use"
```

**Comment by cyrilchapon** [comment] 2020-03-26 00:10
Hey @entropitor ; thanks for this.

This gives 

```
bash: nvm: command not found
```

**Comment by entropitor** [comment] 2020-03-26 07:52
Hmmm, I guess that your bash is not set up to run nvm. Which gives me more confidence this is not a problem with `dotenv-cli`, I'm closing this but feel free to ask more questions.

What is your normal shell you use? If it's zsh use
```
dotenv -- zsh -c "nvm use"
```

**Closed by entropitor** 2020-03-26 07:52 UTC
